Feature/mr 45/members post put
BaSP-m2023/baru-megarocket-app pull request #10
Opened 2023-05-31 01:40 UTC by FontanR

In this PR the methods POST and PUT were developed for members resource.
We should get a modal with a message both in succes and error paths.

2023-05-31 03:00 UTC, francoax requested changes

2023-05-31 03:00 UTC, francoax commented on src/Components/Members/index.js
> +  const [modalMessage, setModalMessage] = useState(null);
we can set all these states on the top to organize better the code

2023-05-31 03:00 UTC, francoax commented on src/Components/Members/Form/index.js
> +      console.log(memberId);
we can remove this console log

2023-06-01 01:22 UTC, francoax approved these changes

2023-06-01 17:25 UTC, BareaMartin approved these changes

2023-06-01 17:25 UTC, merged