BaSP-MR-235: Change form for desktop mode
BaSP-m2023/baru-megarocket-app pull request #116
Opened 2023-07-15 00:26 UTC by santimenendez98

Changed all forms to look good in desktop mode, separating them into columns when necessary.
The forms changed were:

- Edit member form
- Sign up
- Add trainer form
- Edit trainer form
- Activities form
- Add admin form
- Edit admin form

2023-07-15 06:02 UTC, IgnacioGalceran requested changes
Nice santi, but you just missed the edit of members logged in as an admin
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/99512277/9cf6ba65-26af-4637-a790-dbe63d1cce8a)

2023-07-15 17:54 UTC, IgnacioGalceran approved these changes
Nice santi

2023-07-15 21:14 UTC, MauroCaffesse approved these changes

2023-07-15 21:14 UTC, merged

2023-07-17 18:08 UTC, JulianRiedinger7 commented
Test Passed! Great work