BaSP-MR-49: Activities CRUD
BaSP-m2023/baru-megarocket-app pull request #12
Opened 2023-05-31 22:16 UTC by francoax

Development done:
- Display of activities list. 
- Create, edit and delete of activities.

2023-05-31 22:56 UTC, MauroCaffesse requested changes

2023-05-31 22:56 UTC, MauroCaffesse commented on src/Components/Activities/Modals/Delete/deleteModal.module.css
> +  background-color: rgb(0, 0, 0);
To maintain consistency in the code, you can use one color format in the styles.

2023-05-31 22:56 UTC, MauroCaffesse commented on src/Components/Activities/Table/List.jsx
> +import { useState, useEffect } from 'react';
```suggestion
import React, { useState, useEffect } from 'react';
```
You should import React, like this for example

2023-05-31 22:56 UTC, MauroCaffesse commented on src/Components/Activities/index.jsx
> +import { useState, useEffect } from 'react';
```suggestion
import React, { useState, useEffect } from 'react';
```
Also here

2023-05-31 23:14 UTC, MauroCaffesse approved these changes
Good job!

2023-06-01 01:25 UTC, BareaMartin approved these changes

2023-06-01 01:25 UTC, merged