BaSP-MR-48: Members GET-DELETE
BaSP-m2023/baru-megarocket-app pull request #2
Opened 2023-05-30 02:40 UTC by francoax

Development done:
- Display of members list
- Delete button in the list
- Search filter in the list

2023-05-30 15:56 UTC, FontanR approved these changes
LGTM

2023-05-30 21:45 UTC, JuanMornik requested changes

2023-05-30 21:45 UTC, JuanCruzMoreira commented on src/Components/Members/Modal/deletemodal.module.css
> +  background-color: rgb(0, 0, 0);
Please keep consistency in colors language (use hex or rgb throughout the file)

2023-05-30 21:45 UTC, JuanMornik commented on src/Components/Members/Toast/toast.module.css
> +  box-shadow: 0px 10px 23px rgba(0, 0, 0, 0.12);
color name consistency

2023-05-30 22:40 UTC, JuanMornik requested changes

2023-05-30 22:40 UTC, JuanMornik commented on src/Components/Members/index.jsx
> +import { useEffect, useState } from 'react';
import "React" too

2023-05-30 22:40 UTC, JuanMornik commented on src/Components/Members/index.jsx
> +      console.log(res);
Delete this console.log()

2023-05-31 13:42 UTC, JuanMornik approved these changes

2023-06-01 01:10 UTC, merged