BaSP-MR-87: Class shared components
BaSP-m2023/baru-megarocket-app pull request #28
Opened 2023-06-06 22:10 UTC by IgnacioGalceran

All shared components were applied to the 'Class' feature, including modals, inputs, and buttons. The entire routing management was done using react-router-dom.

2023-06-06 23:42 UTC, josedaniele requested changes

2023-06-06 23:42 UTC, josedaniele commented on src/Components/Classes/List/ClassList.jsx
> +            ? 'Are you sure you want to create this class?'
this should just be "are you sure you want to delete this class?" and no update or create

2023-06-07 01:37 UTC, josedaniele requested changes

2023-06-07 01:37 UTC, josedaniele commented on src/Components/Classes/index.jsx
> +          'Something went wrong :( try again later'
this should be  'There are not classes yet. Add new ones!!'  like in the correction of my pr

2023-06-07 01:47 UTC, MauroCaffesse requested changes

2023-06-07 01:47 UTC, MauroCaffesse commented on src/Components/Classes/List/list.module.css
>  }
The styles below this comment are not being used and serve no purpose. They should be deleted to maintain cleaner code.

2023-06-07 02:57 UTC, MauroCaffesse approved these changes

2023-06-07 13:05 UTC, josedaniele approved these changes

2023-06-07 13:13 UTC, merged