BaSP-MR-77: Members
BaSP-m2023/baru-megarocket-app pull request #29
Opened 2023-06-07 00:25 UTC by FontanR

**Implement shared components and react routes.
The index of the resource members should display a list like this**
![member index](https://github.com/BaSP-m2023/baru-megarocket-app/assets/123534779/5dddd4c5-6d5e-4c2e-8faa-ba5778b0159b)

**The form should be empty when adding a new member**
![member form](https://github.com/BaSP-m2023/baru-megarocket-app/assets/123534779/5bd05113-b6d5-4b22-bcf8-f1c3a63bb710)

**And should bring the data to the form in case we are editting**
![member edit](https://github.com/BaSP-m2023/baru-megarocket-app/assets/123534779/19cfc1ae-9989-4e00-acd0-460bc4580feb)

**In every single endpoint you should watch a modal that requires a confirmation to the action**
![confirm modal](https://github.com/BaSP-m2023/baru-megarocket-app/assets/123534779/d2b10fc4-2954-4bea-96a1-16d1687f2f7e)

**And when you confirm should take you to the index page with the updated list of members showing a toast on the top of the page depending the endpoint and the result**
![member toast](https://github.com/BaSP-m2023/baru-megarocket-app/assets/123534779/f8c00a5a-e37b-4523-8696-e8f2817d3bba)

**CLARIFICATIONS:
Cant create a new member with a membership of "Only Classes" (backend error)
The slide bottom from the member list in the index have no functionality**

2023-06-07 12:55 UTC, MauroCaffesse commented on src/Components/Members/Form/index.jsx
> +        console.log(error);
Please delete this console.log

2023-06-07 12:55 UTC, MauroCaffesse commented on src/Components/Members/index.jsx
>        console.log(error);
Also this one

2023-06-07 13:48 UTC, francoax requested changes

2023-06-07 13:48 UTC, francoax commented on src/Components/Members/Form/index.jsx
> +      editMember = member;
Here, instead of have to declare every attribute, you can directly do
```suggestion
      editMember = { ...member }
```
 You are setting above the attributes for the member, so you know that member has the necessary things.

2023-06-07 13:48 UTC, francoax commented on src/Components/Members/Form/form.module.css
You can change all the "modal" from the classes, because they are no more modals.

2023-06-07 13:48 UTC, francoax commented on src/Components/Members/Form/index.jsx
> +  let [editMember, setEditMember] = useState(null);
for useState, declare it as `const`, no with `let`

2023-06-07 13:48 UTC, francoax commented on src/Components/Members/Form/index.jsx
> +  let [member, setMember] = useState({
same here, use `const`

2023-06-07 13:48 UTC, francoax commented on src/Components/Members/index.jsx
> +        <button className={`${styles['btn-new']}`}>+ Add new</button>
Now we have a shared button component. Use it here !!

2023-06-07 22:00 UTC, francoax approved these changes

2023-06-08 00:15 UTC, MauroCaffesse approved these changes

2023-06-08 00:46 UTC, IgnacioGalceran approved these changes

2023-06-08 00:46 UTC, merged