BaSP-MR-41: Subscriptions Get and Post
BaSP-m2023/baru-megarocket-app pull request #3
Opened 2023-05-30 14:24 UTC by jramire5

Get and Post enpoints for Subscription.

2023-05-30 21:48 UTC, JuanMornik requested changes

2023-05-30 21:48 UTC, JuanMornik commented on src/Components/Subscriptions/Form-Create/form.module.css
> +  background-color: rgba(0, 0, 0, 0.45);
Please keep consistency in color language

2023-05-30 21:48 UTC, JuanMornik commented on src/Components/Subscriptions/index.jsx
> +  // const [subscriptionById, setSubscriptionById] = useState([]);
Delete commented lines please

2023-05-30 22:06 UTC, JuanMornik reviewed
Edir PR title please

2023-05-30 22:18 UTC, JuanMornik requested changes

2023-05-30 22:18 UTC, JuanMornik commented on src/Components/Subscriptions/Form-Create/index.jsx
> +  console.log(subscription.classes);
delete this console.log please

2023-05-31 00:48 UTC, santimenendez98 commented on src/Components/Subscriptions/Table/index.jsx
> +                <td className={styles.item}>{subscription.date}</td>
This date should show a date in easy format, for example (MM/DD/YYYY)

2023-05-31 00:49 UTC, santimenendez98 approved these changes

2023-05-31 00:54 UTC, jramire5 commented on src/Components/Subscriptions/Table/index.jsx
> +                <td className={styles.item}>{subscription.date}</td>
Perfect, lets change it when we merge the tables!

2023-05-31 00:55 UTC, jramire5 commented on src/Components/Subscriptions/Table/index.jsx
> +                <td className={styles.item}>{subscription.date}</td>
So we take it from your table

2023-05-31 14:08 UTC, JuanMornik approved these changes

2023-05-31 14:36 UTC, merged