MR-106: GET class with redux
BaSP-m2023/baru-megarocket-app pull request #37
Opened 2023-06-10 20:28 UTC by IgnacioGalceran

Implement Redux on the resource 'Class' (GET method).
Setup of reducer in the rootReducer.js file
combineReducers({
  classes: classReducer
});
Added three different constants and actions in constants.js and actions.js files (GET PENDING, GET SUCCESS and GET ERROR).
Added reducer and thunk logic in the respectives files.

2023-06-10 20:35 UTC, josedaniele requested changes

2023-06-10 20:35 UTC, josedaniele commented on src/Components/Classes/index.jsx
>          'There are not classes yet. Add new ones!!'
This message should only appear once when no classes are retrieved, and not simultaneously with the spinner.

2023-06-10 21:59 UTC, josedaniele approved these changes

2023-06-10 22:01 UTC, francoax approved these changes

2023-06-10 23:10 UTC, FontanR commented on src/Components/Classes/index.jsx
> +      {console.log(classes.length, pending)}
delete this console.log

2023-06-10 23:39 UTC, merged

2023-06-11 19:01 UTC, JulianRiedinger7 commented
Tests passed succesfully! Great Work!