BaSP-MR-43: Class GET - GETBYID - POST
BaSP-m2023/baru-megarocket-app pull request #4
Opened 2023-05-30 15:03 UTC by IgnacioGalceran

Display of classes list (Get)
Create form for classes (Post)
Select of a class (GetById)
Search filter in the class list

2023-05-30 16:34 UTC, josedaniele requested changes

2023-05-30 16:34 UTC, josedaniele commented on src/Components/Classes/Form/Form.jsx
> +      Object.values(classes).every((el) => {
What is "el"? Could you give it a more representative name?

2023-05-30 16:34 UTC, josedaniele commented on src/Components/Classes/Form/Form.jsx
> +                ) : null}
can include an error condition where "classes.time === 0 "  to prevent making a server call.

2023-05-30 17:21 UTC, josedaniele approved these changes

2023-05-30 22:47 UTC, JuanMornik requested changes

2023-05-30 22:47 UTC, JuanMornik commented on src/Components/Classes/index.jsx
> +import { useState, useEffect } from 'react';
Import React too
`import React, { useEffect, useState } from 'react';
`

2023-05-31 14:10 UTC, JuanMornik approved these changes

2023-05-31 14:12 UTC, JuanMornik requested changes

2023-05-31 14:12 UTC, JuanMornik commented on src/Components/Classes/List/list.module.css
> +  background-color: #373867 !important;
Delete all !important in css files

2023-05-31 14:51 UTC, IgnacioGalceran commented on src/Components/Classes/List/list.module.css
> +  background-color: #373867 !important;
done!

2023-05-31 14:54 UTC, JuanMornik approved these changes

2023-05-31 14:54 UTC, merged