BaSP-MR-110: Members redux development
BaSP-m2023/baru-megarocket-app pull request #41
Opened 2023-06-13 20:14 UTC by FontanR

Implementation of redux in members resource

Page should look the same way (no changes applied to the view) but now with redux we can handle a bit better the toast functionality.
Toast should disappear from the view a few seconds after it appears but this could be fast foward if the user clicked a link or over the toast itself.
In addition, a loader was added for the resource index while waiting for the api data to load that sohuld be displayed in the center of the page and with the same colors of the header and footer design.

2023-06-13 21:01 UTC, francoax requested changes
The button `Add new member` its shown when the table is loading and when you want to create or edit a member, the confirm modal doesn't disappear after click on the submit button if you have some mistakes in the form.

If you want, you can change the text for the button "Add new member" to  " + Add new " to continue with the consistency with the team

2023-06-13 21:02 UTC, francoax commented
> The button `Add new member` its shown when the table is loading and when you want to create or edit a member, the confirm modal doesn't disappear after click on the submit button if you have some mistakes in the form.
> 
> If you want, you can change the text for the button "Add new member" to " + Add new " to continue with the consistency with the team

However, everything works perfect !! Good job

2023-06-14 02:48 UTC, MauroCaffesse requested changes

2023-06-14 02:48 UTC, MauroCaffesse commented on src/Components/Members/Form/index.jsx
> +        console.log(error);
Please delete this console.log()

2023-06-14 13:49 UTC, MauroCaffesse approved these changes
Great Job!!

2023-06-14 14:28 UTC, francoax approved these changes

2023-06-14 14:51 UTC, merged