BaSP-MR-105: Add redux to put and delete subscription
BaSP-m2023/baru-megarocket-app pull request #44
Opened 2023-06-13 21:40 UTC by santimenendez98

Add redux for subscriptions, modify the form file with all the asynchronous functions in the thunk file, these functions are put in global states.
For the put request, edit the form by accessing the global states for each input, using the get request to access members and classes, pressing submit on the form and getting a success response, it will return a successful modal if everything went well and you it will return to the table, and if the request was wrong it leaves you in the form and shows you an error modal.
And for the delete, use an asynchronous function that will delete the object with the id and return a modal

2023-06-13 23:54 UTC, francoax requested changes
Be carefull, in the list there is a Loop of requests and in the Edit doesn't work if you only change an input and I think is due to you are sending an object and I think you have to send the respective ID of the class or member

2023-06-13 23:55 UTC, francoax commented
The delete works !! Nice

2023-06-14 00:48 UTC, jramire5 commented on src/Redux/Subscriptions/thunks.js
> +        const updatedSubscriptions = subscriptions.map((sub) => {
line 37-45 are needed? , i mean, where are you using the subscription saved on the set?
Can be done on a global variable using redux?

2023-06-14 18:21 UTC, francoax approved these changes

2023-06-15 03:18 UTC, jramire5 commented on src/Redux/rootReducer.js
> -  activities: activititesReducer,
delete this change, is crashing activities

2023-06-15 03:18 UTC, jramire5 commented on src/Redux/Subscriptions/thunks.js
> +  putSubscriptionSuccess,
change put to edit in order to gain consistency

2023-06-15 03:18 UTC, jramire5 commented on src/Redux/Subscriptions/thunks.js
> +  putSubscriptionSuccess,
and also because in actions is already changed... Why it's working?

2023-06-15 18:20 UTC, jramire5 approved these changes
Subscriptions is working!

2023-06-15 18:22 UTC, merged

2023-06-16 13:26 UTC, JulianRiedinger7 reviewed
Tests passed succesfully!

2023-06-16 21:55 UTC, gabiholl commented
Some changes should be done but good job! [https://trello.com/c/nKhH9oe2](url)