BaSP-MR-98: Superadmin
BaSP-m2023/baru-megarocket-app pull request #46
Opened 2023-06-13 23:01 UTC by victoriassol

This PR is related to ticket: https://trello.com/c/7HZrj5tF/98-week-13-superadmin

- Implemented Redux in the resource in order to handle the components' states better.
- CRUD actions were updated.
- A new "Loader" component was added when the Superadmins list is being fetched.

2023-06-14 00:33 UTC, francoax commented on src/Redux/SuperAdmins/thunks.js
> +const responseInfo = { resState: '', resMessage: '', superadmins: [] };
I saw this and I searched if you are using it but no, only in the error actions, but after that payload is unused. I think you can remove this.

2023-06-14 00:37 UTC, francoax commented
Everything works perfect !! Nice

2023-06-14 00:37 UTC, francoax approved these changes

2023-06-14 17:32 UTC, WalterArielPavicich requested changes

2023-06-14 17:32 UTC, WalterArielPavicich commented on src/Components/SuperAdmins/Form/index.jsx
>    const getItemById = async () => {
try-catch could be added

2023-06-14 17:32 UTC, WalterArielPavicich commented on src/Components/SuperAdmins/Form/index.jsx
>    const getItemById = async () => {
and I think this request should be moved to the "thunks" file

2023-06-14 22:30 UTC, victoriassol commented on src/Components/SuperAdmins/Form/index.jsx
>    const getItemById = async () => {
> and I think this request should be moved to the "thunks" file

I was not able to do so but I found another way of removing the request altogether!

2023-06-15 00:41 UTC, WalterArielPavicich commented on src/Components/SuperAdmins/Form/index.jsx
>    const getItemById = async () => {
You found a very good solution! Everything looks good and works perfect! Great job!

2023-06-15 00:41 UTC, WalterArielPavicich approved these changes
You found a very good solution! Everything looks good and works perfect! Great job!

2023-06-15 14:03 UTC, merged

2023-06-15 17:19 UTC, JulianRiedinger7 reviewed
All tests passed! Great work! Only remains to fix the delete functionality!