BaSP-MR-130: Member Profile created using React's useForm hook.
BaSP-m2023/baru-megarocket-app pull request #57
Opened 2023-06-19 15:41 UTC by MauroCaffesse

Implement the member profile feature with the ability to edit their own profile using React's useForm hook.

Adapt the login functionality to utilize useForm for testing member profiles.

Access the profile by clicking on the name and photo in the header next to the Logout button.

Editing the profile requires clicking the white pencil button located on the right side of the profile, enabling input fields and buttons for resetting and confirming the edits.

If any field is empty or contains an error, the confirmation modal will not open until the input is correct. 

If all fields are correct, the profile will be updated and the user will be redirected to the Home page.

2023-06-19 19:31 UTC, josedaniele requested changes
Still can't find why but admins path, classes and subscription are broken check it

2023-06-19 20:35 UTC, josedaniele approved these changes

2023-06-19 21:03 UTC, IgnacioGalceran approved these changes

2023-06-19 21:13 UTC, merged

2023-06-22 00:30 UTC, matiasluispeter reviewed
It is ok!