BaSP-Feature/MR-133: Forms member admins superadmins
BaSP-m2023/baru-megarocket-app pull request #59
Opened 2023-06-19 22:27 UTC by FontanR

Change shared input. Now it receives 2 new props: register (for handeling data in the inputs) and error (for handeling the messages from the validations).

Implement absolutes routes for the imports.

implement react hook forms and joi for the validations in the following entitys: members, admins and super admins.

Page should look similar to last week but now it should display messages below every input when user dont comply a validation.

Add a new reset button that should turn every input blank again in case we are adding a new one and should reset the original data from the entity the user want to edit.

**Page should look like this**
![PR](https://github.com/BaSP-m2023/baru-megarocket-app/assets/123534779/024ae59e-e49a-44bd-8dcc-aa49c2976554)

2023-06-19 23:57 UTC, victoriassol requested changes

2023-06-19 23:57 UTC, victoriassol commented on src/Validations/admin.js
> +  }),
I would write these rules to only accept numbers:
phone: Joi.string()
    .pattern(/^[0-9]+$/)
    .min(10)
    .max(15)
    .required()
    .messages({
      'string.pattern.base': 'Phone Number should only contain numbers',
      'string.base': 'Phone Number should be a string',
      'string.empty': 'Phone Number is required',
      'string.min': 'Phone Number should have a minimum length of 10',
      'string.max': 'Phone Number should have a maximum length of 15'
    }),

2023-06-19 23:57 UTC, victoriassol commented on src/Validations/admin.js
> +    'any.required': 'City is required'
```suggestion
    'string.empty': 'City is required'
```

2023-06-19 23:57 UTC, victoriassol commented on src/Validations/admin.js
> +    'any.required': 'City is required'
This rule showcases the correct custom message when the field is left empty! (instead of '"city" is not allowed to be empty')

2023-06-19 23:57 UTC, victoriassol commented on src/Validations/admin.js
> +      'any.required': 'First Name is required'
```suggestion
      'string.empty': 'First Name is required'
```

2023-06-19 23:57 UTC, victoriassol commented on src/Validations/admin.js
> +      'any.required': 'Last Name is required'
```suggestion
       'string.empty': 'Last Name is required'
```

2023-06-19 23:57 UTC, victoriassol commented on src/Validations/admin.js
> +      'string.pattern.base': 'Password should have numbers and letters between 6 and 20 characters'
```suggestion
      'string.pattern.base': 'Password should have numbers and letters between 6 and 20 characters',
      'string.empty': 'Password is required'
```

2023-06-20 01:37 UTC, victoriassol approved these changes

2023-06-20 04:01 UTC, francoax requested changes
If I want to edit just the membership status, there is an error of **"i is undefined"**

2023-06-20 05:50 UTC, jramire5 commented
Cannot Update a Member
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/42724273/cfc86f6e-10a9-41be-a806-a9b07800fc75)

2023-06-20 16:38 UTC, jramire5 approved these changes
Everything is working and everithing is looking good. Good Job!

2023-06-20 16:40 UTC, francoax commented
Nice !!! Good work

2023-06-20 16:40 UTC, francoax approved these changes

2023-06-20 17:02 UTC, merged

2023-06-20 17:19 UTC, gabiholl commented
Great job! works fine!