BaSP-Feature/MR-135: Forms Activities Classes Subscriptions Trainers
BaSP-m2023/baru-megarocket-app pull request #62
Opened 2023-06-20 05:44 UTC by jramire5

Change shared input. Now it receives 2 new props: register (for handling data in the inputs) and error

Implement Absolute routes for the imports in forms.

Implement react hook forms and joi for the validations in the following entitys: Activities Classes Subscriptions Trainers

Implement react-select library for selects. 

Page should look like last week but now it should display messages below every input if a validation fails.

Add a new reset button that should turn every input blank again in case we are adding a new one and should reset the original data from the entity the user want to edit. (Classes and Trainers)

2023-06-20 20:07 UTC, FontanR reviewed
Try to be more consistent with the messages from the validations
Besides that, everything works great
Excellent job!

2023-06-20 20:07 UTC, FontanR commented on src/Validations/trainer.js
> +  email: Joi.string().required(),
make a stronger validation for email

2023-06-20 20:07 UTC, FontanR commented on src/Components/Subscriptions/index.jsx
>          />
if you use a placeholder the label is not needed

2023-06-20 22:43 UTC, FontanR approved these changes

2023-06-21 00:52 UTC, josedaniele requested changes

2023-06-21 00:52 UTC, josedaniele commented on src/Validations/trainer.js
> +      'string.empty': 'Dni is required'
Write DNI to maintain consistency with the message above

2023-06-21 00:52 UTC, josedaniele commented on src/Components/Classes/List/ClassList.jsx
>  import { refreshData } from '../../../Redux/Classes/actions';
you could use absolute paths

2023-06-21 02:22 UTC, josedaniele approved these changes

2023-06-21 22:13 UTC, merged