BaSP-MR-132: Admin profile
BaSP-m2023/baru-megarocket-app pull request #63
Opened 2023-06-20 16:41 UTC by victoriassol

Created an admin profile where you're able to edit their information and delete the profile.
The profile grabs the first admin on the list and showcases that data.
Implemented react hook forms library and absolute imports.

2023-06-20 18:51 UTC, josedaniele requested changes
note that the spinner of the loader is off center, fix that.
Everything else works perfectly, good job.

2023-06-20 18:51 UTC, josedaniele commented on src/Components/Admins/Form/index.jsx
> +import adminSchema from '../../../Validations/admin';
please apply absolute paths

2023-06-20 18:51 UTC, josedaniele commented on src/Components/Admins/Profile/index.jsx
> +import adminSchema from '../../../Validations/admin';
same here

2023-06-20 20:36 UTC, josedaniele approved these changes

2023-06-20 23:11 UTC, WalterArielPavicich commented on src/Components/Admins/Profile/index.jsx
> +      {defaultAdmin == {} && <p>There are no admins</p>}
I think that the empty object couldn't be evaluated this way, I found this way that works!

```suggestion
      {Object.keys(defaultAdmin).length === 0 && <p>There are no admins</p>}
```

2023-06-20 23:22 UTC, WalterArielPavicich commented on src/Components/Admins/Profile/profile.module.css
> +  box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 7px 20px 0 rgba(0, 0, 0, 0.17);
could change rgba to hex

2023-06-20 23:32 UTC, WalterArielPavicich commented on src/Redux/Admins/actions.js
> +    type: 'SET_DEFAULT_ADMIN',
could be added to constants.js file and imported from there
```suggestion
    type: SET_DEFAULT_ADMIN,
```

2023-06-20 23:33 UTC, WalterArielPavicich commented on src/Redux/Admins/reducers.js
> +    case 'SET_DEFAULT_ADMIN': {
same here

```suggestion
    case SET_DEFAULT_ADMIN: {
```

2023-06-21 15:30 UTC, victoriassol commented on src/Components/Admins/Profile/index.jsx
> +      {defaultAdmin == {} && <p>There are no admins</p>}
awesome, thank you!

2023-06-21 18:17 UTC, WalterArielPavicich approved these changes
Everything works very well! Great job!

2023-06-21 20:41 UTC, merged

2023-06-23 20:59 UTC, gabiholl commented
Its fixed! works fine!