BaSP-MR-152: Redux auth config
BaSP-m2023/baru-megarocket-app pull request #68
Opened 2023-06-24 00:15 UTC by victoriassol

Added login, signup and logout thunks, reducers and actions to be implemented in the UI.
Added the token header to each resource's thunks so that it checks for authorization in every request.
Initialized firebase.

2023-06-24 00:23 UTC, francoax requested changes

2023-06-24 00:23 UTC, francoax commented on src/Firebase/index.js
This file is not necessary because in the setup @santimenendez98 has already created

2023-06-24 02:14 UTC, WalterArielPavicich commented on src/Redux/Auth/thunks.js
> +import { firebaseApp } from '../../helper/firebase';
change relative to absolute route

2023-06-24 23:51 UTC, santimenendez98 approved these changes
Nice!

2023-06-25 18:12 UTC, francoax approved these changes

2023-06-25 19:39 UTC, WalterArielPavicich commented on src/Redux/Auth/thunks.js
> +      const response = fetch(`${process.env.REACT_APP_API_URL}/api/auth/`, { headers: { token } });
await is missing

```suggestion
      const response = await fetch(`${process.env.REACT_APP_API_URL}/api/auth/`, { headers: { token } });
```

2023-06-25 22:52 UTC, merged