BaSP-MR-50: Class put and delete component
BaSP-m2023/baru-megarocket-app pull request #7
Opened 2023-05-30 19:17 UTC by josedaniele

In this PR, the functionalities to update and delete a user were implemented along with their respective modals for success and error messages. The view utilized the GET request that my teammate developed in their ticket. Additionally, the mapping in this GET request was modified to render a component called "DataViewTd," which made data editing easier for me.

2023-05-30 21:02 UTC, IgnacioGalceran approved these changes
Everything works!

2023-05-30 23:52 UTC, JuanMornik requested changes

2023-05-30 23:52 UTC, JuanMornik commented on src/Components/Classes/List/list.module.css
> +  background-color: #373867 !important;
Delete all "!important"

2023-05-31 16:57 UTC, JuanMornik requested changes

2023-05-31 16:57 UTC, JuanMornik commented on src/Components/Classes/List/DataViewTd/DataViewTd.jsx
> +import React from 'react';
Write both imports in the same line

2023-05-31 16:57 UTC, JuanMornik commented on src/Components/Classes/List/ClassList.jsx
> +import { useState } from 'react';
Add React too

2023-05-31 17:05 UTC, JuanMornik approved these changes

2023-05-31 17:05 UTC, merged