BaSP-MR-147: Private routes and navigation bar for different entities
BaSP-m2023/baru-megarocket-app pull request #71
Opened 2023-06-26 02:47 UTC by josedaniele

Private Routes for ADMIN:

The ADMIN entity now has access to the "Classes" , enabling them to manage and oversee class-related functionalities .
They can navigate through the "Activities" section, allowing them to create, edit, and see activities .
Access to the "Subscriptions" .
ADMIN users can view the comprehensive "Members" list, enabling them to manage user information.
Private Routes for MEMBER:

MEMBER entities now have access to the "Activities" section
They can access the "Subscriptions" zone to review and manage their own subscriptions
Private Routes for SUPERADMIN:

SUPERADMIN entities have access  to manage ADMIN and SUPERADMIN users.
para probar el logueo de distintas entidades puedes usar los siguientes mails

To test the logging of different entities you can use the following emails:
MEMBER:
firstmember1@gmail.com
ADMIN:
secondadmin@gmail.com
SUPER ADMIN:
superadmin2@gmail.com
the password for everyone is Abc123456

2023-06-26 03:32 UTC, santimenendez98 approved these changes

2023-06-26 03:53 UTC, WalterArielPavicich commented on src/Components/Header/index.js
> +    sessionStorage.removeItem('role');
is redundant

2023-06-26 14:27 UTC, santimenendez98 requested changes

2023-06-26 14:27 UTC, santimenendez98 commented on src/Components/Header/index.js
> +              <Link to="/super-admins" className={styles.a}>
This part is not necessary.

2023-06-26 14:27 UTC, santimenendez98 commented on src/Routes/index.jsx
> +            />
This parts too

2023-06-26 14:27 UTC, santimenendez98 commented on src/Components/Header/index.js
> +          {role === 'SUPER_ADMIN' && (
In this part maybe the source path should be added

2023-06-26 15:22 UTC, santimenendez98 approved these changes

2023-06-26 15:24 UTC, WalterArielPavicich approved these changes
Great job!

2023-06-26 15:27 UTC, merged

2023-07-01 19:44 UTC, gabiholl commented
There were some bugs reported in the next sections:
Admin classes https://trello.com/c/Eb5YGBzb 
Admin members https://trello.com/c/mMKQcCDf 

Superadmin: review bugs reported by QA partner Julián Riedinger
The rest of the itemps seem to work as expected.