BaSP-MR-174: update subscription in member route and fixed bug enroll it
BaSP-m2023/baru-megarocket-app pull request #72
Opened 2023-06-26 20:44 UTC by josedaniele

This pull request . Firstly, it restores the functionality of the logged-in member routes, which were previously not working . Secondly, it resolves a bug that allowed members to subscribe multiple times to the same class.

Details of the changes made in this pull request:

Fixed member routes: The routes for the logged-in member have been re-implemented and are now fully functional. Members can access the appropriate sections and perform actions related to activities and subscriptions as intended.

Resolved subscription bug:  This issue has been fixed, and now the system properly validates and prevents duplicate subscriptions.

2023-06-27 00:16 UTC, santimenendez98 requested changes
When I unsubscribe from a subscription, the page removes all subscriptions, but when I refresh the page, they appear.

2023-06-27 03:51 UTC, santimenendez98 approved these changes

2023-06-27 14:19 UTC, MauroCaffesse approved these changes
Great Job! Congrats!

2023-06-27 14:32 UTC, merged

2023-06-28 17:22 UTC, JulianRiedinger7 commented
Great Work!