BaSP-MR-44: Superadmin CRUD
BaSP-m2023/baru-megarocket-app pull request #8
Opened 2023-05-30 20:44 UTC by victoriassol

2023-05-31 13:23 UTC, WalterArielPavicich commented on src/Components/SuperAdmins/index.js
> +  const handleUpdateClick = async (id) => {
```suggestion
  const handleUpdateClick = async (id) => {
  try {
```

2023-05-31 13:24 UTC, WalterArielPavicich commented on src/Components/SuperAdmins/index.js
> +    setUpdatingItem(data.data);
```suggestion
    setUpdatingItem(data.data);
    catch (error) {
```

2023-05-31 13:26 UTC, WalterArielPavicich requested changes
Try - catch can be added in handleUpdateClick

2023-05-31 18:55 UTC, WalterArielPavicich approved these changes

2023-05-31 19:41 UTC, JuanMornik requested changes

2023-05-31 19:41 UTC, JuanMornik commented on src/Components/SuperAdmins/Form/Form.js
File name must be index.jsx
It's important that the extension be '.jsx' because is a react component

2023-05-31 19:41 UTC, JuanMornik commented on src/Components/SuperAdmins/MessageModal/MessageModal.js
File name must be index.jsx
It's important that the extension be '.jsx' because is a react component

2023-05-31 19:41 UTC, JuanMornik commented on src/Components/SuperAdmins/Table/Table.js
File name must be index.jsx
It's important that the extension be '.jsx' because is a react component

2023-05-31 19:52 UTC, victoriassol commented on src/Components/SuperAdmins/Table/Table.js
done!

2023-05-31 19:58 UTC, JuanMornik requested changes

2023-05-31 19:58 UTC, JuanMornik commented on src/Components/SuperAdmins/index.jsx
> +import Form from './Form/Form';
Update imports

2023-05-31 20:13 UTC, JuanMornik requested changes

2023-05-31 20:13 UTC, JuanCruzMoreira commented on src/Components/SuperAdmins/Form/index.jsx
> +                    type="text"
This must be type="password"

2023-06-01 01:20 UTC, BareaMartin approved these changes

2023-06-01 01:21 UTC, merged