BaSP-MR-189: Folders restruct
BaSP-m2023/baru-megarocket-app pull request #84
Opened 2023-07-02 20:30 UTC by francoax

Development to respond [Trello-MR#189](https://trello.com/c/GgJlIdkv)

### New
- Four folders created: **Admins, Members, SuperAdmins and Trainers**, where each type of user has their respective views.
- New Routing. Now there are respective files for each type of user. If you want to declare new ones, you will need to go to the respective file and create it there.

### Fixes
- I fixed all the imports on each file to follow a consistency. I recommend working as follows:

    **[ imports from libraries and styles ]**
    _-- space --_
    **[ imports related to thunks, functions, etc...]**
    _-- space --_
    **[imports related to components]**
    _-- space --_

2023-07-02 22:00 UTC, santimenendez98 requested changes
Nice job! One thing for fix is when the admin creates a trainer, its returns "fail to fetch".

2023-07-03 13:28 UTC, santimenendez98 approved these changes

2023-07-03 16:54 UTC, jramire5 reviewed
Cannot edit member
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/42724273/316996fb-198e-4ecf-a4d8-779e06e965f8)
Cannot see members list as an admin
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/42724273/f92fc158-51d0-427d-b22c-e9cbb2639d37)

2023-07-04 03:58 UTC, jramire5 approved these changes
Good Job!

2023-07-04 03:59 UTC, merged