BaSP-MR-198: Logic and validations for class subscribed and capacity
BaSP-m2023/baru-megarocket-app pull request #86
Opened 2023-07-04 20:41 UTC by jramire5

Now, it should add one to subscribed on class when a member subscribes to a class. And rest one when a member unsubscribes. If a class has equal subscribed members to capacity, it shouldn't let subscribe to this class

2023-07-05 18:06 UTC, josedaniele requested changes
When I subscribe to a class and then unsubscribe, the number of subscribed members does not decrease, it remains the same.
step 1 i subscribe to football
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/94631305/a415e1f0-450b-4512-b689-38b5b9edd20b)

step 2 the numbers of subscribed increase in 1
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/94631305/5cb201f7-af84-4dd7-87ef-5b02d5d3d8da)
step 3 i unsubscribed of the class
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/94631305/4a38643f-d84f-4287-bee3-1e4ccabff948)
step 4 the class has the same number of enrollees
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/94631305/faca8591-83ec-4c98-bafa-e9bf4aaa0a2d)

2023-07-06 16:07 UTC, jramire5 commented
@josedaniele I think this is solved

2023-07-06 17:23 UTC, josedaniele approved these changes

2023-07-06 17:42 UTC, josedaniele requested changes

2023-07-06 17:42 UTC, josedaniele commented on src/Components/Admins/Subscriptions/Form/index.jsx
> +        console.log(subClass);
delete this console.log

2023-07-06 17:42 UTC, josedaniele commented on src/Components/Admins/Subscriptions/Table/index.jsx
> +    console.log(subClass);
and this

2023-07-06 17:42 UTC, josedaniele commented on src/Components/Members/SubscriptionsMember/index.jsx
> +    console.log(subscriptionEdited);
and this

2023-07-06 17:42 UTC, josedaniele commented on src/Redux/Classes/thunks.js
> +      console.log('response', response);
and this

2023-07-06 22:07 UTC, IgnacioGalceran approved these changes
nice!

2023-07-07 18:52 UTC, MauroCaffesse approved these changes

2023-07-08 21:32 UTC, josedaniele approved these changes

2023-07-08 22:22 UTC, merged