BaSP-MR-194: Change input filter
BaSP-m2023/baru-megarocket-app pull request #89
Opened 2023-07-05 01:23 UTC by santimenendez98

The entry style of the filter in each entity was changed, the color of the title was also changed and in the subscription filter activity was added to filter, before only members could be filtered.
In addition to this, a column was added in the subscription table, this column contains the date of each class and the column classes now contain the activity that is performed

Titles:
![title](https://github.com/BaSP-m2023/baru-megarocket-app/assets/127548159/be7d2073-056d-471c-ab6f-6305f5da6289)
Inputs:
![inputs](https://github.com/BaSP-m2023/baru-megarocket-app/assets/127548159/6ebab8a7-a3e3-4c16-be4f-6aa38d3e41a4)
Now the subscription table it look like this:
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/127548159/3b210361-c0a1-4ac4-a620-6e9145352452)

2023-07-05 22:53 UTC, josedaniele requested changes
in the subscriptions table the class appears undefined
![image](https://github.com/BaSP-m2023/baru-megarocket-app/assets/94631305/3d3b39ea-ae0c-4f55-8c41-bb2cdcfc2e13)

2023-07-06 17:45 UTC, josedaniele requested changes

2023-07-06 17:45 UTC, josedaniele commented on src/Components/Admins/Subscriptions/Table/index.jsx
> +                  <Link to={`/subscriptions/edit/${subscription._id}`}>
this must be
`<Link to={`/user/admin/subscriptions/edit/${subscription._id}`}>`
the previous path no longer works

2023-07-06 22:10 UTC, josedaniele approved these changes

2023-07-06 22:14 UTC, IgnacioGalceran approved these changes
well done

2023-07-06 22:21 UTC, merged