BaSP-MR-203: Changed Thunks methods on Subscriptions
BaSP-m2023/baru-megarocket-app pull request #90
Opened 2023-07-05 03:24 UTC by jramire5

Updated the way of using dispatch on Redux Thunks of Subscriptions

2023-07-05 13:57 UTC, victoriassol approved these changes

2023-07-05 18:24 UTC, WalterArielPavicich requested changes

2023-07-05 18:24 UTC, WalterArielPavicich commented on src/Redux/Subscriptions/thunks.js
> +    dispatch(editSubscriptionPending);
only the parentheses are missing

```suggestion
    dispatch(editSubscriptionPending());
```

2023-07-06 18:24 UTC, WalterArielPavicich approved these changes

2023-07-06 18:39 UTC, IgnacioGalceran approved these changes

2023-07-06 18:40 UTC, josedaniele approved these changes

2023-07-06 18:49 UTC, merged